[build]
  command = "npm run migrate:deploy && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure we don't try to build Prisma binary during the build
[functions]
  node_bundler = "esbuild" 